<?php

namespace ContainerWoF7EWW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_81yOsNVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.81yOsNV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.81yOsNV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productSubCategory' => ['privates', '.errored..service_locator.81yOsNV.App\\Entity\\ProductSubCategory', NULL, 'Cannot autowire service ".service_locator.81yOsNV": it references class "App\\Entity\\ProductSubCategory" but no such service exists.'],
        ], [
            'productSubCategory' => 'App\\Entity\\ProductSubCategory',
        ]);
    }
}
