<?php

namespace ContainerWoF7EWW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DDxCb1fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dDxCb1f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dDxCb1f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'productSubCategory' => ['privates', '.errored..service_locator.dDxCb1f.App\\Entity\\ProductSubCategory', NULL, 'Cannot autowire service ".service_locator.dDxCb1f": it references class "App\\Entity\\ProductSubCategory" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'productSubCategory' => 'App\\Entity\\ProductSubCategory',
        ]);
    }
}
