<?php

namespace ContainerWoF7EWW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductCategory2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hsTZOkm.App\Entity\ProductCategory' shared service.
     *
     * @return \App\Entity\ProductCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hsTZOkm": it references class "App\\Entity\\ProductCategory" but no such service exists.');
    }
}
