<?php

namespace ContainerWoF7EWW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductSubCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.81yOsNV.App\Entity\ProductSubCategory' shared service.
     *
     * @return \App\Entity\ProductSubCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.81yOsNV": it references class "App\\Entity\\ProductSubCategory" but no such service exists.');
    }
}
