<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWoF7EWW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWoF7EWW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWoF7EWW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWoF7EWW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWoF7EWW\App_KernelDevDebugContainer([
    'container.build_hash' => 'WoF7EWW',
    'container.build_id' => '40b62841',
    'container.build_time' => 1707600685,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWoF7EWW');
