<?php

namespace ContainerX2ME0Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X8X8vqkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X8X8vqk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X8X8vqk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productSubCategoryRepository' => ['privates', 'App\\Repository\\ProductSubCategoryRepository', 'getProductSubCategoryRepositoryService', true],
        ], [
            'productSubCategoryRepository' => 'App\\Repository\\ProductSubCategoryRepository',
        ]);
    }
}
