<?php

namespace ContainerX2ME0Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HsTZOkmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hsTZOkm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hsTZOkm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productCategory' => ['privates', '.errored..service_locator.hsTZOkm.App\\Entity\\ProductCategory', NULL, 'Cannot autowire service ".service_locator.hsTZOkm": it references class "App\\Entity\\ProductCategory" but no such service exists.'],
        ], [
            'productCategory' => 'App\\Entity\\ProductCategory',
        ]);
    }
}
